BookLibrary/BookLibrary.Web/Controllers/SearchBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookLibrary.Data.Models;
using BookLibrary.Data.Repositories;

namespace BookLibrary.Web.Controllers
{
    /// <summary>
    /// Search Books Controller
    /// </summary>
    public class SearchBooksController : Controller
    {
        private IBookRepository _bookrepository;

        public SearchBooksController(IBookRepository bookrepository)
        {
            this._bookrepository = bookrepository;

        }

        // GET: SearchBooks
        public async Task<ActionResult> Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Find(string query)
        {
            try
            {
                ViewBag.CurrentFilter = query;

                if (!string.IsNullOrEmpty(query))
                {
                    string strSearchBy = Request.Form["searchBy"];
                    Session["SearchBy"] = ViewBag.SearchBy = strSearchBy;
                    if (strSearchBy == "Author" && !string.IsNullOrWhiteSpace(query))
                    {
                        IEnumerable<Book> books = await _bookrepository.GetBooksByAuthor(query);
                        return View("Index", books);
                    }
                    else if (strSearchBy == "BookName" && !string.IsNullOrWhiteSpace(query))
                    {
                        IEnumerable<Book> books = await _bookrepository.GetBooksByName(query);
                        return View("Index", books);
                    }

                }

                var all_books = await _bookrepository.GetBooks();
                return View("Index", all_books);
            }
            catch (Exception ex)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }

        // GET: Books/Delete/5
        public async Task<ActionResult> Lend(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var book = _bookrepository.GetBookByID((int)id);

            Task result;

            Task continuation = book.ContinueWith(x => result = _bookrepository.LendBook(x.Result));

            var all_books = _bookrepository.GetBooks();

            await Task.WhenAll(continuation, all_books);

            if (book == null)
            {
                return HttpNotFound();
            }

            return View("Index", all_books.Result);

        }

        // GET: Books/Delete/5
        public async Task<ActionResult> Return(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var book = _bookrepository.GetBookByID((int)id);

            Task result;

            Task continuation =  book.ContinueWith(x => result = _bookrepository.ReturnBook(x.Result));
          

            var all_books = await _bookrepository.GetBooks();


            if (book == null)
            {
                return HttpNotFound();
            }

            return View("Index", all_books);

        }
    }

}

BookLibrary/BookLibrary.Web/Views/SearchBooks/Create.cshtml
@model BookLibrary.Data.Models.Book

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorId, "AuthorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookLibrary/BookLibrary.Web/Views/SearchBooks/Delete.cshtml
@model BookLibrary.Data.Models.Book

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookLibrary/BookLibrary.Web/Views/SearchBooks/Details.cshtml
@model BookLibrary.Data.Models.Book

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BookLibrary/BookLibrary.Web/Views/SearchBooks/Edit.cshtml
@model BookLibrary.Data.Models.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorId, "AuthorId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BookLibrary/BookLibrary.Web/Views/SearchBooks/Index.cshtml
@model IEnumerable<BookLibrary.Data.Models.Book>

@{
    ViewBag.Title = "Search Book";
}

<h2>Books Finder</h2>

<div style='font-family:Arial'>
    @using (Html.BeginForm("Find", "SearchBooks", FormMethod.Post))
    {
        <div >
            <b>Search by:   </b>
            @Html.TextBox("query", ViewBag.CurrentFilter as string)
            <br />

            @Html.RadioButton("searchBy", "Author", true)<text>Author</text>
            
            @if (ViewBag.SearchBy == "BookName")
            {
                @Html.RadioButton("searchBy", "BookName", true)<text>Book Name</text>
            }
            else
            {
                @Html.RadioButton("searchBy", "BookName")<text>Book Name</text>
            }
        </div>
        <br />
        <div >
            <input type="submit" value="Find" class="btn btn-default" />
        </div>
        <br />
    }

</div>
@if(Model != null)
{ 
<table class="table">
    <tr>
        <th>
            Book Name
        </th>
        <th>
            Category
        </th>
        <th>
            Author Name
        </th> 
        <th>
            Available copy
        </th> 
        <th>
            Lend\Return        
        </th> 
    </tr>

@foreach (var item in Model.Select((value, i) => new { Data = value, Index = i }))
{
    <tr class=@(item.Index % 2 == 0 ? "even" : "odd")>
        <td>
            @Html.DisplayFor(modelItem => item.Data.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data.Author.Fullname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data.Stock)
        </td>
        <td>
            @Html.ActionLink("Lend", "Lend", new { id = item.Data.Id }, new { @class = "edit", title = "Lend Book" }) |
            @Html.ActionLink("Return", "Return", new { id = item.Data.Id }, new { @class = "details", title = "Return Book" }) 
        </td>
    </tr>
}

</table>
}